services:
  psbt-signer:
    build: ./psbt-signer
    container_name: psbt-signer
    restart: unless-stopped
    environment:
      SERVICE_NAME: psbt-signer
      NETWORK: test
      BTC-NETWORK_IP: 192.168.99.58
      BTC-NETWORK_PORT: 18443

      DATABASE_URL: postgresql://user:pass@postgres:5432/btc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: btc
      
    volumes:
      - /var/lib/signer/data:/psbt-signer/run/data
      - /var/lib/signer/wallets:/psbt-signer/run/wallets
      - /var/lib/signer/tpm:/psbt-signer/tpm
      - ./psbt-signer/app:/psbt-signer/scripts:ro
      - /var/lib/signer/hmac.secret:/psbt-signer/run/secrets/hmac.secret:ro

    devices:
      - /dev/tpm0:/dev/tpm0
      - /dev/tpmrm0:/dev/tpmrm0

    ports:
     - "8080:8080"
     
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: btc
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/run/postgresql/data
    - ./psbt-signer/app/001_psbt.sql:/docker-entrypoint-initdb.d/001_psbt.sql:ro

volumes:
  postgres_data: