services:
  psbt-signer:
    build: ./psbt-signer
    restart: unless-stopped
    user: "1000:1000"

    volumes:
      - /var/lib/signer/data:/psbt-signer/run/data
      - /var/lib/signer/wallets:/psbt-signer/run/wallets
      - ./psbt-signer/app:/psbt-signer/scripts:ro
      - /var/lib/signer/hmac.secret:/psbt-signer/run/secrets/hmac.secret:ro

    #command: ["python3", "/scripts/signer.py"]

    environment:
      NETWORK: regtest
    devices:
      - /dev/tpm0:/dev/tpm0
      - /dev/tpmrm0:/dev/tpmrm0