table inet filter
delete table inet filter 

table inet filter {

  chain input {
    type filter hook input priority 0;
    policy drop;

    iif lo accept
    ct state established,related accept

    iifname "wg0" accept
    iifname "eth0" udp dport 51820 accept
  }

  chain output {
    type filter hook output priority 0;
    policy drop;

    oif lo accept
    ct state established,related accept

    oifname "wg0" accept
    oifname "eth0" udp sport 51820 accept #für handshake
  }
}