table inet filter
delete table inet filter

table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;
    iif lo accept
    ct state established,related accept
    iifname "wg0" accept
    iifname "eth0" udp dport 51820 accept
  }
  chain output {
    type filter hook output priority 0; policy accept;   # Setup: Egress offen für docker build/pull
  }
}