ruleset-setup = ''
table inet filter {

  chain input {
    type filter hook input priority 0;
    policy drop;

    iif lo accept
    ct state established,related accept

    # wg erlaubt
    iif "wg0" accept
  }

  chain output {
    type filter hook output priority 0;
    policy drop;

    oif lo accept
    ct state established,related accept

    #Zugriff auf Regtest Node
    ip daddr 192.168.99.101 tcp dport 18443 accept

    # wg erlaubt
    oif "wg0" accept
  }
}
'';