ruleset-locked = ''
table inet filter {

  chain input {
    type filter hook input priority 0;
    policy drop;

    iif lo accept
    ct state established,related accept

    iif "wg0" accept
  }

  chain output {
    type filter hook output priority 0;
    policy drop;

    oif lo accept
    ct state established,related accept

    oif "wg0" ip daddr 192.168.99.78 accept
  }
}
'';