worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 64;
}

http {
    server_tokens off; 

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    # Nur kleine PSBT-JSON-Bodies
    client_max_body_size 2m;

    #Nur ein peer, flood schutz
    limit_req_zone $binary_remote_addr zone=sign:1m rate=5r/s;

    server {
        listen 8080;

        location /sign {
            #Flood schutz
            limit_req zone=sign burst=5 nodelay;
            limit_except POST { deny all; }

            proxy_pass http://psbt-signer:8080/sign;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        #Abweisen
        location / {
            return 404;
        }
    }
}
